In [18]:
## Turple
my_tuple = (1, 'hello', [3, 4], (5, 6))

#print(my_tuple[0])  # Accessing the first element of the tuple
#print(my_tuple[2])  # Accessing the third element of the tuple

c = (1,)
print(c[0])
t = 1, 2

print(type(t))

a, b = t
print(t[0])
print(t[1])

1
<class 'tuple'>
1
2


In [14]:
## List
colours = ['red',1,'blue','yellow']
i = 0
for i in colours[0::3]:
    print(i)
    
print(colours[2])

print(type(colours))

red
yellow
blue
<class 'list'>


In [28]:
## Dictionary

my_dict = {
 "name":"yanjun",
 "age" :28,
 "city":"Stockholm"
}

print(my_dict["name"])
print(my_dict["age"])

for i,k in my_dict.items():
   print(i,k)

yanjun
28
name yanjun
age 28
city Stockholm


In [1]:
print_info()

NameError: name 'print_info' is not defined

def print_info():
    my_dict = {
    "name":"yanjun",
    "age" :29,
    "city":"Stockholm"
    }
    for i,k in my_dict.items():
        print(i,k)
    return my_dict.items()

print_info()

In [1]:
import print_info
c = print_info.print_info()
d = print_info.yanjun()


name yanjun
age 28
city Stockholm
yanjun is so cool!


In [2]:
def yanjun():
    #a = print("yanjun is so cool!")
    return "yanjun is so cool!"
yanjun()

'yanjun is so cool!'

In [31]:
def Annual_income(x):
    s = x*13
    return s


print(Annual_income(30000))

390000


In [36]:
import sys

input_file = sys.argv[1]

# Now you can use 'input_file' in your script to refer to the provided input file
print("Input file:", input_file)


Input file: -f


In [40]:
import math 
print(math.sin(math.pi/3))

0.8660254037844386


In [22]:
def print_mult_table1(n):
   for i in range(1,6):
      print(i*7)

## check the programme run as a module or main programme
if __name__ != "__main__":
    import sys
    print_mult_table1 (int(sys.argv[1]),2) 

#print_mult_table1(5)

In [15]:
print(sys.argv[1])

-f


In [11]:
def print_mult_table1(n):
    # Print the multiplication table of 'n' up to 5
    for i in range(1, 6):
        print(i * n)

# Check if the script is being run as the main program
if __name__ == "__main__":
    import sys
    
    # Check if the correct number of command-line arguments is provided
    if len(sys.argv) != 2:
        print("Usage: python script.py <number>")
        sys.exit(1)  # Exit the script with a non-zero exit status
    
    # Get the number from the command-line argument and convert it to an integer
    number = int(sys.argv[1])
    
    # Call the function with the provided number
    print_mult_table1(number)

Usage: python script.py <number>


SystemExit: 1

In [15]:
print('This is a poem:', 2)
L = [5,3,4,8,1]
L.sort()
print(L.sort)

This is a poem: 2
<built-in method sort of list object at 0x7af4c46ac680>


In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [18]:
import requests
from IPython.display import Image, HTML
url = f'https://jsdokken.com/dolfinx-tutorial/#'
r = requests.get(url)
print(r)

<Response [200]>


In [19]:
display(
Image(
    url='https://images.nationalgeographic.org/image/upload/t_edhub_resource_key_image/v1638886301/EducationHub/photos/lightning-bolts.jpg'
    )
)

In [10]:
import numpy as np
arr = np.array([
    [1,2,3], 
    [4,5,6],
])

print("Array:"     )
print(arr)

Array:
[[1 2 3]
 [4 5 6]]


In [16]:
print("Shape:", arr.shape)
print("Data type:", arr.dtype)
print("Element at (0, 1):", arr[0, 1])
print("Array * 2:")
print(arr * 2)
mat = np.array([[1, 2], [3, 4]])
print("Matrix multiplication:")
print(np.dot(mat, mat))

Shape: (2, 3)
Data type: int64
Element at (0, 1): 2
Array * 2:
[[ 2  4  6]
 [ 8 10 12]]
Matrix multiplication:
[[ 5 11]
 [11 25]]


In [17]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
print("Broadcasting:")
print(a + b)

Broadcasting:
[[11 22 33]
 [14 25 36]]


In [26]:
!xdg-open https://yanjun96.github.io/Blog/