In [2]:
import numpy as np

In [3]:
np.array([6,28,496,8128])

array([   6,   28,  496, 8128])

In [4]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [5]:
np.zeros(4)

array([0., 0., 0., 0.])

In [6]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.empty(4)

array([0., 0., 0., 0.])

In [8]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [9]:
np.logspace(1,-1,3)

array([10. ,  1. ,  0.1])

In [10]:
c = np.logspace(1,-1,3)

In [11]:
a = np.arange(8)

In [12]:
a[::-1]

array([7, 6, 5, 4, 3, 2, 1, 0])

In [13]:
a[2:6]

array([2, 3, 4, 5])

In [25]:
a = np.arange(16)

In [15]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [20]:
a.shape=(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [22]:
a[1:3, 1:3]


array([[ 5,  6],
       [ 9, 10]])

In [28]:
a.shape=(2,8)
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


loop in numpy is expensive