In [1]:
import numpy as np

In [3]:
np.array([6,28,496,8128])

array([   6,   28,  496, 8128])

In [4]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [5]:
np.zeros(4)

array([0., 0., 0., 0.])

In [6]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.empty(4)

array([0., 0., 0., 0.])

In [8]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [9]:
np.logspace(1,-1,3)

array([10. ,  1. ,  0.1])

In [10]:
c = np.logspace(1,-1,3)

In [11]:
a = np.arange(8)

In [12]:
a[::-1]

array([7, 6, 5, 4, 3, 2, 1, 0])

In [13]:
a[2:6]

array([2, 3, 4, 5])

In [25]:
a = np.arange(16)

In [15]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [20]:
a.shape=(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [22]:
a[1:3, 1:3]


array([[ 5,  6],
       [ 9, 10]])

In [28]:
a.shape=(2,8)
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


loop in numpy is expensive

In [8]:
a = np.arange(4)
a.shape = (2,2)
print(a)

[[0 1]
 [2 3]]


In [9]:
b = np.array([[42], [43]])

In [10]:
a*b

array([[  0,  42],
       [ 86, 129]])

In [11]:
np.dot(a,b)

array([[ 43],
       [213]])

In [6]:
a = np.arange(12)
a.shape = (4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [10]:
b = np.array([16,17,18,19])
print(b)

[16 17 18 19]


In [5]:
a + b

array([[16, 18, 20],
       [19, 21, 23],
       [22, 24, 26],
       [25, 27, 29]])

In [11]:
a.shape = (3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
a + b

array([[16, 18, 20, 22],
       [20, 22, 24, 26],
       [24, 26, 28, 30]])

In [14]:
a = 2*np.arange(8)**2 + 1
print(a)

[ 1  3  9 19 33 51 73 99]


In [15]:
a[[3,-1,-1]]

array([19, 99, 99])

In [26]:
a[ [[2, 7], [4, 2] ] ]


array([[ 9, 99],
       [33,  9]])

In [2]:
a = np.arange(16) - 8
a.shape = (4,4)
i = np.arange(4)
a[i, i]

array([-8, -3,  2,  7])

In [3]:
a = np.arange(9)
a.shape = (3,3)
m = np.ones(3, dtype=bool)
a[m,m]

array([0, 4, 8])

In [9]:
m = (a<5)
a[m]

array([0, 1, 2, 3, 4])

In [12]:
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
np.where(a<5) #the output is the coordinates , like 0,1 0,2 0,3, it means 1, 2, 3

(array([0, 0, 0, 1, 1]), array([0, 1, 2, 0, 1]))